### ISSUE TITLE
detrend.py needs docstrings

### ISSUE THREAD

**Issue by ekaterinailin** [jradavenport/appaloosa#12]
FitSin() and most of the other functions in detrend.py would benefit from concise docstrings that explain the method and its purpose. 
@jradavenport Could you pick this one up? Meanwhile, I'm working on the rest.

**Comment by jradavenport** [comment]
I'll work on that YES!

**Comment by jradavenport** [comment]
[NOW](https://github.com/jradavenport/appaloosa/commit/2a584574040c429172a845d278bd7c112b725c2d) with a TON more docstrings!
